version: "2.0"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8181

  nginx:
      build: ./nginx
      container_name: nginx_dockerproject
      restart: always
      ports:
      - "81:81"

